
mysql:
    debug: true  # mysql 调试开关
    addr: 127.0.0.1:3306
    dbName: ipcc
    userName: root
    password: Aa123456!@#

# Redis配置
redis:
  addr: 127.0.0.1:6379
  password:

common:
  loglevel: DEBUG
  #logPath : /Users/Peter/Downloads
